### ISSUE TITLE
Vertical Scroll/Pagination on Layout changes results in wrong scroll position

### ISSUE THREAD

**Issue by Secretmapper** [n4kz/react-native-pages#9] opened 2017-07-03 12:11 UTC
How to reproduce:

Create a multi paged, vertical layout. When switching from landscape to portrait and vice versa, the scroll position would sometimes end up 'in the middle' so to speak.

Furthermore, if a layout change is triggered by say the keyboard (text input inside pager), it would also result in the wrong scroll position.

**Comment by n4kz** [comment] 2017-07-04 08:40
Thanks for reporting! Fixed in `0.5.2`. Looks like problem was caused by unwanted `onScroll` event, produced by native `ScrollView` implementations during layout updates.

**Closed by n4kz** 2017-07-04 08:40 UTC

**Comment by Secretmapper** [comment] 2017-07-05 04:25
Thanks for the quick turn around @n4kz! I just tested it and it works as far as I tested :)
